name: CD Pipeline

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    environment: staging

    env:
      DEPLOY_ENV: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: bash module-06-deploy/deploy.sh
